server:
  port: 8001
eureka:
  client:
    service-url: #eureka 注册中心的地址，用于client 与 server进行交流
      defaultZone: http://localhost:7001/eureka/
#### 数据库连接池属性
spring:
  application:
    name: cloud-provider-payment
