server:
  port: 53020

spring:
  application:
    name: discributed-uua
  main:
    allow-bean-definition-overriding: true

#### thymeleaf 配置
  thymeleaf:
    prefix: classpath:/templates/  #设置thymeleaf路径默认为src/main/resources/templates
    suffix: .html  #设置thymeleaf模板后缀
    cache: false  #是否开启缓存默认为true
    encoding: UTF-8    #设置编码

#### 数据库连接池属性
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/user_db?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root
    #自动提交
    default-auto-commit: true
    #指定updates是否自动提交
    auto-commit: true
    maximum-pool-size: 100
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
    validation-query: SELECT 1
    test-on-borrow: false
    test-while-idle: true
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 18800
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000

# mybatis对应的映射文件路径
mybatis:
  mapper-locations: classpath:mapper/*.xml
  # mybatis对应的实体类
  type-aliases-package: com.moding.springcloud.springsecuritydistributeduaa.model

logging:
  config: classpath:logback-spring.xml
