server:
  port: 9090
spring:
  application:
    name: resource-server
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url: #eureka 注册中心的地址，用于client 与 server进行交流
      defaultZone: http://localhost:7001/eureka/