server:
  port: 80
eureka:
  client:
    service-url: #eureka 注册中心的地址，用于client 与 server进行交流
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/,http://localhost:7003/eureka/
#### 数据库连接池属性
spring:
  application:
    name: microservicecloud-dept-consumer