server:
  port: 9527
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url: #eureka 注册中心的地址，用于client 与 server进行交流
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://localhost:7001/eureka/

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #payment_route # 路由ID,没有固定规则但是要求唯一，建议配合服务名
          uri: lb://CLOUD-PROVIDER-PAYMENT #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** # 断言，路径相匹配的路由

        - id: payment_routh2 #payment_route # 路由ID,没有固定规则但是要求唯一，建议配合服务名
          uri: lb://CLOUD-PROVIDER-PAYMENT #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/** # 断言，路径相匹配的路由
            #- After=2020-03-25T22:01:45.354+08:00[Asia/Shanghai] #在指定时间以后才可以访问
            #- Before=2021-03-25T22:01:45.354+08:00[Asia/Shanghai] #在指定时间以前才可以访问
            #- Between=2017-01-20T17:42:47.789-07:00[America/Denver], 2017-01-21T17:42:47.789-07:00[America/Denver] #在指定时间之间可以访问
            #- Cookie=chocolate, ch.p #cookies 含有chocolate名字，并且值符合ch.p表达式（正则）
            #- Header=X-Request-Id, \d+ #header中含有X-Request-Id 值是数字
            #- Host **.somehost.org,**.anotherhost.org #匹配请求头中的host属性
            #- Method=GET,POST
            #- Query=green # 携带green参数 http://localhost:9527/payment/lb?green=1
            #- RemoteAddr=192.168.1.1/24
            #- Weight=group1, 2 # 权重 定义组group1和百分比20% 将20%流量转发到uri指定的地址
          filters:
            - Pre #PreGatewayFilterFactory这里注意类名去掉GatewayFilterFactory 否则找不到

