server:
  port: 80
eureka:
  client:
    service-url: #eureka 注册中心的地址，用于client 与 server进行交流
      defaultZone: http://localhost:7001/eureka/
#### 数据库连接池属性
spring:
  application:
    name: cloud-consumer-order
  zipkin:
    base-url: http://localhost:9411
    sleuth:
      sampler:
        #采样率值介于0到1之间，1则表示全部采集
        probability: 1