server:
  port: 3344
eureka:
  client:
    service-url: #eureka 注册中心的地址，用于client 与 server进行交流
      defaultZone: http://localhost:7001/eureka/
#### 数据库连接池属性
spring:
  application:
    name: cloud-config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/waldron-xing/mystudy-springcloud.git
          search-paths:
            - cloud2020/cloud-config
          username: waldron_xing@163.com
          password: waldron1987
      label: master

