server:
  port: 7001
eureka:
  instance:
    hostname: peer-3
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    register-with-eureka: false #表明该服务不会向Eureka Server注册自己的信息
    fetch-registry: false #表明该服务不会向Eureka Server获取注册信息
    service-url: #eureka 注册中心的地址，用于client 与 server进行交流
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eureka-service