server:
  port: 9091
spring:
  application:
    name: authorization-server
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    service-url: #eureka 注册中心的地址，用于client 与 server进行交流
      defaultZone: http://localhost:7001/eureka/

security:
  oauth2:
    client:
      client-id: first-client
      client-secret: noonewilleverguess